### ISSUE TITLE
Fault on api key registration

### ISSUE THREAD

**Issue by mirek967** [Cutleast/SSE-Auto-Translator#7]
Trying to register an api key during setup leads to following error:

Traceback (most recent call last):
  File "H:\SSE-AT\widgets\api_setup.py", line 86, in check_api_key
  File "H:\SSE-AT\translation_provider\nm_api\nm_api.py", line 65, in check_api_key
  File "H:\SSE-AT\translation_provider\nm_api\nm_api.py", line 91, in request
AttributeError: 'NoneType' object has no attribute 'get_from_web_cache'

This happen under linux system with proton.

**Comment by mirek967** [comment]
Full log from program run.

**Comment by Cutleast** [comment]
Thanks for reporting the issue! It's fixed in the next update.

**Comment by mirek967** [comment]
Thank you very much. 
Do you have any plan regarding future releases?
I wonder also if it will be possible to compile and run it in native linux system.

**Comment by Cutleast** [comment]
Since this error isn't critical and can be worked around, it'll come with the planned v2.1 (see README.md for link to Roadmap on Trello).

It would be very difficult to build SSE-AT for Linux because some of the libs I use are Windows only.
